CREATE ROLE "adminDB" WITH
    LOGIN
    SUPERUSER
    INHERIT
    CREATEDB
    CREATEROLE
    NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'password';

CREATE DATABASE "SHOOTING_GALLERY"
    WITH 
    OWNER = "adminDB"
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;